import type { Metadata } from 'next';
import { Inter, Roboto_Mono, Urbanist } from 'next/font/google';

import '../../globals.css';
import Navbar from './components/navbar/navbar.component';

import SessionWrapper from './components/session-wrapper/session-wrapper.component';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blvk Rvbbit | Admin',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang='en'>
        <body className={inter.className}>
          <Navbar />
          <div className='container relative top-[6rem]'>{children}</div>
        </body>
      </html>
    </SessionWrapper>
  );
}
