import type { Metadata } from 'next';
import { Inter, Roboto_Mono, Urbanist } from 'next/font/google';
import Navbar from './components/navbar/navbar.component';
import '../globals.css';

const inter = Inter({ subsets: ['latin'] });
const roboto_mono = Roboto_Mono({ subsets: ['latin'] });
const urbanist = Urbanist({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blvk Rvbbit | Home',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`dark-theme ${roboto_mono.className}`}>
        <Navbar />
        <div className='relative top-[6rem]'>{children}</div>
      </body>
    </html>
  );
}
